# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: history_plant_proto_pool.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import request_login_pb2 as request__login__pb2
import response_login_pb2 as response__login__pb2
import request_logout_pb2 as request__logout__pb2
import response_logout_pb2 as response__logout__pb2
import request_reference_data_pb2 as request__reference__data__pb2
import response_reference_data_pb2 as response__reference__data__pb2
import reject_pb2 as reject__pb2
import request_tick_bar_replay_pb2 as request__tick__bar__replay__pb2
import response_tick_bar_replay_pb2 as response__tick__bar__replay__pb2
import request_tick_bar_update_pb2 as request__tick__bar__update__pb2
import response_tick_bar_update_pb2 as response__tick__bar__update__pb2
import request_time_bar_replay_pb2 as request__time__bar__replay__pb2
import response_time_bar_replay_pb2 as response__time__bar__replay__pb2
import request_time_bar_update_pb2 as request__time__bar__update__pb2
import response_time_bar_update_pb2 as response__time__bar__update__pb2
import request_historical_last_trade_pb2 as request__historical__last__trade__pb2
import response_historical_last_trade_pb2 as response__historical__last__trade__pb2
import tick_bar_pb2 as tick__bar__pb2
import time_bar_pb2 as time__bar__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='history_plant_proto_pool.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x1ehistory_plant_proto_pool.proto\x1a\x13request_login.proto\x1a\x14response_login.proto\x1a\x14request_logout.proto\x1a\x15response_logout.proto\x1a\x1crequest_reference_data.proto\x1a\x1dresponse_reference_data.proto\x1a\x0creject.proto\x1a\x1drequest_tick_bar_replay.proto\x1a\x1eresponse_tick_bar_replay.proto\x1a\x1drequest_tick_bar_update.proto\x1a\x1eresponse_tick_bar_update.proto\x1a\x1drequest_time_bar_replay.proto\x1a\x1eresponse_time_bar_replay.proto\x1a\x1drequest_time_bar_update.proto\x1a\x1eresponse_time_bar_update.proto\x1a#request_historical_last_trade.proto\x1a$response_historical_last_trade.proto\x1a\x0etick_bar.proto\x1a\x0etime_bar.proto')
  ,
  dependencies=[request__login__pb2.DESCRIPTOR,response__login__pb2.DESCRIPTOR,request__logout__pb2.DESCRIPTOR,response__logout__pb2.DESCRIPTOR,request__reference__data__pb2.DESCRIPTOR,response__reference__data__pb2.DESCRIPTOR,reject__pb2.DESCRIPTOR,request__tick__bar__replay__pb2.DESCRIPTOR,response__tick__bar__replay__pb2.DESCRIPTOR,request__tick__bar__update__pb2.DESCRIPTOR,response__tick__bar__update__pb2.DESCRIPTOR,request__time__bar__replay__pb2.DESCRIPTOR,response__time__bar__replay__pb2.DESCRIPTOR,request__time__bar__update__pb2.DESCRIPTOR,response__time__bar__update__pb2.DESCRIPTOR,request__historical__last__trade__pb2.DESCRIPTOR,response__historical__last__trade__pb2.DESCRIPTOR,tick__bar__pb2.DESCRIPTOR,time__bar__pb2.DESCRIPTOR,])



_sym_db.RegisterFileDescriptor(DESCRIPTOR)


# @@protoc_insertion_point(module_scope)
