# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: instrument_pnl_position_update.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='instrument_pnl_position_update.proto',
  package='rti',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n$instrument_pnl_position_update.proto\x12\x03rti\"\xe2\x05\n\x1bInstrumentPnLPositionUpdate\x12\x15\n\x0btemplate_id\x18\xe3\xb6\t \x02(\x05\x12\x15\n\x0bis_snapshot\x18\xa9\xdc\x06 \x01(\x08\x12\x10\n\x06\x66\x63m_id\x18\x9d\xb3\t \x01(\t\x12\x0f\n\x05ib_id\x18\x9e\xb3\t \x01(\t\x12\x14\n\naccount_id\x18\x98\xb3\t \x01(\t\x12\x10\n\x06symbol\x18\x94\xdc\x06 \x01(\t\x12\x12\n\x08\x65xchange\x18\x95\xdc\x06 \x01(\t\x12\x16\n\x0cproduct_code\x18\x8d\x93\x06 \x01(\t\x12\x19\n\x0finstrument_type\x18\xa4\xdc\x06 \x01(\t\x12\x16\n\x0c\x66ill_buy_qty\x18\xb9\xb3\t \x01(\x05\x12\x17\n\rfill_sell_qty\x18\xba\xb3\t \x01(\x05\x12\x17\n\rorder_buy_qty\x18\xb5\xb3\t \x01(\x05\x12\x18\n\x0eorder_sell_qty\x18\xb6\xb3\t \x01(\x05\x12\x11\n\x07\x62uy_qty\x18\x94\xb5\t \x01(\x05\x12\x12\n\x08sell_qty\x18\x95\xb5\t \x01(\x05\x12\x1d\n\x13\x61vg_open_fill_price\x18\xc2\xb6\t \x01(\x01\x12\x16\n\x0cmtm_security\x18\x97\xb5\t \x01(\t\x12!\n\x17open_long_options_value\x18\xb1\xcb\t \x01(\t\x12\"\n\x18open_short_options_value\x18\xb2\xcb\t \x01(\t\x12\x1e\n\x14\x63losed_options_value\x18\xb3\xcb\t \x01(\t\x12\x1e\n\x14option_cash_reserved\x18\xb7\xcb\t \x01(\t\x12\x1b\n\x11open_position_pnl\x18\xa1\xca\t \x01(\t\x12 \n\x16open_position_quantity\x18\xa2\xca\t \x01(\x05\x12\x1d\n\x13\x63losed_position_pnl\x18\xa3\xca\t \x01(\t\x12\"\n\x18\x63losed_position_quantity\x18\xa4\xca\t \x01(\x05\x12\x16\n\x0cnet_quantity\x18\xa7\xca\t \x01(\x05\x12\x0f\n\x05ssboe\x18\xd4\x94\t \x01(\x05\x12\x0f\n\x05usecs\x18\xd5\x94\t \x01(\x05')
)




_INSTRUMENTPNLPOSITIONUPDATE = _descriptor.Descriptor(
  name='InstrumentPnLPositionUpdate',
  full_name='rti.InstrumentPnLPositionUpdate',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='template_id', full_name='rti.InstrumentPnLPositionUpdate.template_id', index=0,
      number=154467, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='is_snapshot', full_name='rti.InstrumentPnLPositionUpdate.is_snapshot', index=1,
      number=110121, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='fcm_id', full_name='rti.InstrumentPnLPositionUpdate.fcm_id', index=2,
      number=154013, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ib_id', full_name='rti.InstrumentPnLPositionUpdate.ib_id', index=3,
      number=154014, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='account_id', full_name='rti.InstrumentPnLPositionUpdate.account_id', index=4,
      number=154008, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='symbol', full_name='rti.InstrumentPnLPositionUpdate.symbol', index=5,
      number=110100, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='exchange', full_name='rti.InstrumentPnLPositionUpdate.exchange', index=6,
      number=110101, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='product_code', full_name='rti.InstrumentPnLPositionUpdate.product_code', index=7,
      number=100749, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='instrument_type', full_name='rti.InstrumentPnLPositionUpdate.instrument_type', index=8,
      number=110116, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='fill_buy_qty', full_name='rti.InstrumentPnLPositionUpdate.fill_buy_qty', index=9,
      number=154041, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='fill_sell_qty', full_name='rti.InstrumentPnLPositionUpdate.fill_sell_qty', index=10,
      number=154042, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='order_buy_qty', full_name='rti.InstrumentPnLPositionUpdate.order_buy_qty', index=11,
      number=154037, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='order_sell_qty', full_name='rti.InstrumentPnLPositionUpdate.order_sell_qty', index=12,
      number=154038, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='buy_qty', full_name='rti.InstrumentPnLPositionUpdate.buy_qty', index=13,
      number=154260, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sell_qty', full_name='rti.InstrumentPnLPositionUpdate.sell_qty', index=14,
      number=154261, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='avg_open_fill_price', full_name='rti.InstrumentPnLPositionUpdate.avg_open_fill_price', index=15,
      number=154434, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mtm_security', full_name='rti.InstrumentPnLPositionUpdate.mtm_security', index=16,
      number=154263, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='open_long_options_value', full_name='rti.InstrumentPnLPositionUpdate.open_long_options_value', index=17,
      number=157105, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='open_short_options_value', full_name='rti.InstrumentPnLPositionUpdate.open_short_options_value', index=18,
      number=157106, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='closed_options_value', full_name='rti.InstrumentPnLPositionUpdate.closed_options_value', index=19,
      number=157107, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='option_cash_reserved', full_name='rti.InstrumentPnLPositionUpdate.option_cash_reserved', index=20,
      number=157111, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='open_position_pnl', full_name='rti.InstrumentPnLPositionUpdate.open_position_pnl', index=21,
      number=156961, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='open_position_quantity', full_name='rti.InstrumentPnLPositionUpdate.open_position_quantity', index=22,
      number=156962, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='closed_position_pnl', full_name='rti.InstrumentPnLPositionUpdate.closed_position_pnl', index=23,
      number=156963, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='closed_position_quantity', full_name='rti.InstrumentPnLPositionUpdate.closed_position_quantity', index=24,
      number=156964, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='net_quantity', full_name='rti.InstrumentPnLPositionUpdate.net_quantity', index=25,
      number=156967, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ssboe', full_name='rti.InstrumentPnLPositionUpdate.ssboe', index=26,
      number=150100, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='usecs', full_name='rti.InstrumentPnLPositionUpdate.usecs', index=27,
      number=150101, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=46,
  serialized_end=784,
)

DESCRIPTOR.message_types_by_name['InstrumentPnLPositionUpdate'] = _INSTRUMENTPNLPOSITIONUPDATE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

InstrumentPnLPositionUpdate = _reflection.GeneratedProtocolMessageType('InstrumentPnLPositionUpdate', (_message.Message,), dict(
  DESCRIPTOR = _INSTRUMENTPNLPOSITIONUPDATE,
  __module__ = 'instrument_pnl_position_update_pb2'
  # @@protoc_insertion_point(class_scope:rti.InstrumentPnLPositionUpdate)
  ))
_sym_db.RegisterMessage(InstrumentPnLPositionUpdate)


# @@protoc_insertion_point(module_scope)
