# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message_type.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='message_type.proto',
  package='rti',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x12message_type.proto\x12\x03rti\"$\n\x0bMessageType\x12\x15\n\x0btemplate_id\x18\xe3\xb6\t \x02(\x05')
)




_MESSAGETYPE = _descriptor.Descriptor(
  name='MessageType',
  full_name='rti.MessageType',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='template_id', full_name='rti.MessageType.template_id', index=0,
      number=154467, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=27,
  serialized_end=63,
)

DESCRIPTOR.message_types_by_name['MessageType'] = _MESSAGETYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MessageType = _reflection.GeneratedProtocolMessageType('MessageType', (_message.Message,), dict(
  DESCRIPTOR = _MESSAGETYPE,
  __module__ = 'message_type_pb2'
  # @@protoc_insertion_point(class_scope:rti.MessageType)
  ))
_sym_db.RegisterMessage(MessageType)


# @@protoc_insertion_point(module_scope)
