# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: request_depth_by_order_snapshot.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='request_depth_by_order_snapshot.proto',
  package='rti',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n%request_depth_by_order_snapshot.proto\x12\x03rti\"\x85\x01\n\x1bRequestDepthByOrderSnapshot\x12\x15\n\x0btemplate_id\x18\xe3\xb6\t \x02(\x05\x12\x12\n\x08user_msg\x18\x98\x8d\x08 \x03(\t\x12\x10\n\x06symbol\x18\x94\xdc\x06 \x01(\t\x12\x12\n\x08\x65xchange\x18\x95\xdc\x06 \x01(\t\x12\x15\n\x0b\x64\x65pth_price\x18\xa5\xb6\t \x01(\x01')
)




_REQUESTDEPTHBYORDERSNAPSHOT = _descriptor.Descriptor(
  name='RequestDepthByOrderSnapshot',
  full_name='rti.RequestDepthByOrderSnapshot',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='template_id', full_name='rti.RequestDepthByOrderSnapshot.template_id', index=0,
      number=154467, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='user_msg', full_name='rti.RequestDepthByOrderSnapshot.user_msg', index=1,
      number=132760, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='symbol', full_name='rti.RequestDepthByOrderSnapshot.symbol', index=2,
      number=110100, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='exchange', full_name='rti.RequestDepthByOrderSnapshot.exchange', index=3,
      number=110101, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='depth_price', full_name='rti.RequestDepthByOrderSnapshot.depth_price', index=4,
      number=154405, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=47,
  serialized_end=180,
)

DESCRIPTOR.message_types_by_name['RequestDepthByOrderSnapshot'] = _REQUESTDEPTHBYORDERSNAPSHOT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RequestDepthByOrderSnapshot = _reflection.GeneratedProtocolMessageType('RequestDepthByOrderSnapshot', (_message.Message,), dict(
  DESCRIPTOR = _REQUESTDEPTHBYORDERSNAPSHOT,
  __module__ = 'request_depth_by_order_snapshot_pb2'
  # @@protoc_insertion_point(class_scope:rti.RequestDepthByOrderSnapshot)
  ))
_sym_db.RegisterMessage(RequestDepthByOrderSnapshot)


# @@protoc_insertion_point(module_scope)
