# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: request_account_rms_info.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='request_account_rms_info.proto',
  package='rti',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x1erequest_account_rms_info.proto\x12\x03rti\"\xe6\x01\n\x15RequestAccountRmsInfo\x12\x15\n\x0btemplate_id\x18\xe3\xb6\t \x02(\x05\x12\x12\n\x08user_msg\x18\x98\x8d\x08 \x03(\t\x12\x10\n\x06\x66\x63m_id\x18\x9d\xb3\t \x01(\t\x12\x0f\n\x05ib_id\x18\x9e\xb3\t \x01(\t\x12\x38\n\tuser_type\x18\xb4\xb3\t \x01(\x0e\x32#.rti.RequestAccountRmsInfo.UserType\"E\n\x08UserType\x12\x11\n\rUSER_TYPE_FCM\x10\x01\x12\x10\n\x0cUSER_TYPE_IB\x10\x02\x12\x14\n\x10USER_TYPE_TRADER\x10\x03')
)



_REQUESTACCOUNTRMSINFO_USERTYPE = _descriptor.EnumDescriptor(
  name='UserType',
  full_name='rti.RequestAccountRmsInfo.UserType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='USER_TYPE_FCM', index=0, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='USER_TYPE_IB', index=1, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='USER_TYPE_TRADER', index=2, number=3,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=201,
  serialized_end=270,
)
_sym_db.RegisterEnumDescriptor(_REQUESTACCOUNTRMSINFO_USERTYPE)


_REQUESTACCOUNTRMSINFO = _descriptor.Descriptor(
  name='RequestAccountRmsInfo',
  full_name='rti.RequestAccountRmsInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='template_id', full_name='rti.RequestAccountRmsInfo.template_id', index=0,
      number=154467, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='user_msg', full_name='rti.RequestAccountRmsInfo.user_msg', index=1,
      number=132760, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='fcm_id', full_name='rti.RequestAccountRmsInfo.fcm_id', index=2,
      number=154013, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ib_id', full_name='rti.RequestAccountRmsInfo.ib_id', index=3,
      number=154014, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='user_type', full_name='rti.RequestAccountRmsInfo.user_type', index=4,
      number=154036, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _REQUESTACCOUNTRMSINFO_USERTYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=40,
  serialized_end=270,
)

_REQUESTACCOUNTRMSINFO.fields_by_name['user_type'].enum_type = _REQUESTACCOUNTRMSINFO_USERTYPE
_REQUESTACCOUNTRMSINFO_USERTYPE.containing_type = _REQUESTACCOUNTRMSINFO
DESCRIPTOR.message_types_by_name['RequestAccountRmsInfo'] = _REQUESTACCOUNTRMSINFO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RequestAccountRmsInfo = _reflection.GeneratedProtocolMessageType('RequestAccountRmsInfo', (_message.Message,), dict(
  DESCRIPTOR = _REQUESTACCOUNTRMSINFO,
  __module__ = 'request_account_rms_info_pb2'
  # @@protoc_insertion_point(class_scope:rti.RequestAccountRmsInfo)
  ))
_sym_db.RegisterMessage(RequestAccountRmsInfo)


# @@protoc_insertion_point(module_scope)
