# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: request_oco_order.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='request_oco_order.proto',
  package='rti',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x17request_oco_order.proto\x12\x03rti\"\x9d\x05\n\x0fRequestOCOOrder\x12\x15\n\x0btemplate_id\x18\xe3\xb6\t \x02(\x05\x12\x12\n\x08user_msg\x18\x98\x8d\x08 \x03(\t\x12\x10\n\x06\x66\x63m_id\x18\x9d\xb3\t \x01(\t\x12\x0f\n\x05ib_id\x18\x9e\xb3\t \x01(\t\x12\x14\n\naccount_id\x18\x98\xb3\t \x01(\t\x12\x10\n\x06symbol\x18\x94\xdc\x06 \x03(\t\x12\x12\n\x08\x65xchange\x18\x95\xdc\x06 \x03(\t\x12\x12\n\x08quantity\x18\x84\xeb\x06 \x03(\x05\x12\x0f\n\x05price\x18\xe2\xdd\x06 \x03(\x01\x12\x17\n\rtrigger_price\x18\xff\x8d\t \x03(\x01\x12@\n\x10transaction_type\x18\x83\xeb\x06 \x03(\x0e\x32$.rti.RequestOCOOrder.TransactionType\x12\x31\n\x08\x64uration\x18\x85\xeb\x06 \x03(\x0e\x32\x1d.rti.RequestOCOOrder.Duration\x12\x34\n\nprice_type\x18\x88\xeb\x06 \x03(\x0e\x32\x1e.rti.RequestOCOOrder.PriceType\x12\x15\n\x0btrade_route\x18\x90\xeb\x06 \x03(\t\x12=\n\x0emanual_or_auto\x18\xd6\xb8\t \x03(\x0e\x32#.rti.RequestOCOOrder.OrderPlacement\"$\n\x0fTransactionType\x12\x07\n\x03\x42UY\x10\x01\x12\x08\n\x04SELL\x10\x02\".\n\x08\x44uration\x12\x07\n\x03\x44\x41Y\x10\x01\x12\x07\n\x03GTC\x10\x02\x12\x07\n\x03IOC\x10\x03\x12\x07\n\x03\x46OK\x10\x04\"C\n\tPriceType\x12\t\n\x05LIMIT\x10\x01\x12\n\n\x06MARKET\x10\x02\x12\x0e\n\nSTOP_LIMIT\x10\x03\x12\x0f\n\x0bSTOP_MARKET\x10\x04\"&\n\x0eOrderPlacement\x12\n\n\x06MANUAL\x10\x01\x12\x08\n\x04\x41UTO\x10\x02')
)



_REQUESTOCOORDER_TRANSACTIONTYPE = _descriptor.EnumDescriptor(
  name='TransactionType',
  full_name='rti.RequestOCOOrder.TransactionType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='BUY', index=0, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SELL', index=1, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=509,
  serialized_end=545,
)
_sym_db.RegisterEnumDescriptor(_REQUESTOCOORDER_TRANSACTIONTYPE)

_REQUESTOCOORDER_DURATION = _descriptor.EnumDescriptor(
  name='Duration',
  full_name='rti.RequestOCOOrder.Duration',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='DAY', index=0, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GTC', index=1, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='IOC', index=2, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FOK', index=3, number=4,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=547,
  serialized_end=593,
)
_sym_db.RegisterEnumDescriptor(_REQUESTOCOORDER_DURATION)

_REQUESTOCOORDER_PRICETYPE = _descriptor.EnumDescriptor(
  name='PriceType',
  full_name='rti.RequestOCOOrder.PriceType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='LIMIT', index=0, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MARKET', index=1, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='STOP_LIMIT', index=2, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='STOP_MARKET', index=3, number=4,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=595,
  serialized_end=662,
)
_sym_db.RegisterEnumDescriptor(_REQUESTOCOORDER_PRICETYPE)

_REQUESTOCOORDER_ORDERPLACEMENT = _descriptor.EnumDescriptor(
  name='OrderPlacement',
  full_name='rti.RequestOCOOrder.OrderPlacement',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='MANUAL', index=0, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='AUTO', index=1, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=664,
  serialized_end=702,
)
_sym_db.RegisterEnumDescriptor(_REQUESTOCOORDER_ORDERPLACEMENT)


_REQUESTOCOORDER = _descriptor.Descriptor(
  name='RequestOCOOrder',
  full_name='rti.RequestOCOOrder',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='template_id', full_name='rti.RequestOCOOrder.template_id', index=0,
      number=154467, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='user_msg', full_name='rti.RequestOCOOrder.user_msg', index=1,
      number=132760, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='fcm_id', full_name='rti.RequestOCOOrder.fcm_id', index=2,
      number=154013, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ib_id', full_name='rti.RequestOCOOrder.ib_id', index=3,
      number=154014, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='account_id', full_name='rti.RequestOCOOrder.account_id', index=4,
      number=154008, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='symbol', full_name='rti.RequestOCOOrder.symbol', index=5,
      number=110100, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='exchange', full_name='rti.RequestOCOOrder.exchange', index=6,
      number=110101, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='quantity', full_name='rti.RequestOCOOrder.quantity', index=7,
      number=112004, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='price', full_name='rti.RequestOCOOrder.price', index=8,
      number=110306, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='trigger_price', full_name='rti.RequestOCOOrder.trigger_price', index=9,
      number=149247, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='transaction_type', full_name='rti.RequestOCOOrder.transaction_type', index=10,
      number=112003, type=14, cpp_type=8, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='duration', full_name='rti.RequestOCOOrder.duration', index=11,
      number=112005, type=14, cpp_type=8, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='price_type', full_name='rti.RequestOCOOrder.price_type', index=12,
      number=112008, type=14, cpp_type=8, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='trade_route', full_name='rti.RequestOCOOrder.trade_route', index=13,
      number=112016, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='manual_or_auto', full_name='rti.RequestOCOOrder.manual_or_auto', index=14,
      number=154710, type=14, cpp_type=8, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _REQUESTOCOORDER_TRANSACTIONTYPE,
    _REQUESTOCOORDER_DURATION,
    _REQUESTOCOORDER_PRICETYPE,
    _REQUESTOCOORDER_ORDERPLACEMENT,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=33,
  serialized_end=702,
)

_REQUESTOCOORDER.fields_by_name['transaction_type'].enum_type = _REQUESTOCOORDER_TRANSACTIONTYPE
_REQUESTOCOORDER.fields_by_name['duration'].enum_type = _REQUESTOCOORDER_DURATION
_REQUESTOCOORDER.fields_by_name['price_type'].enum_type = _REQUESTOCOORDER_PRICETYPE
_REQUESTOCOORDER.fields_by_name['manual_or_auto'].enum_type = _REQUESTOCOORDER_ORDERPLACEMENT
_REQUESTOCOORDER_TRANSACTIONTYPE.containing_type = _REQUESTOCOORDER
_REQUESTOCOORDER_DURATION.containing_type = _REQUESTOCOORDER
_REQUESTOCOORDER_PRICETYPE.containing_type = _REQUESTOCOORDER
_REQUESTOCOORDER_ORDERPLACEMENT.containing_type = _REQUESTOCOORDER
DESCRIPTOR.message_types_by_name['RequestOCOOrder'] = _REQUESTOCOORDER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RequestOCOOrder = _reflection.GeneratedProtocolMessageType('RequestOCOOrder', (_message.Message,), dict(
  DESCRIPTOR = _REQUESTOCOORDER,
  __module__ = 'request_oco_order_pb2'
  # @@protoc_insertion_point(class_scope:rti.RequestOCOOrder)
  ))
_sym_db.RegisterMessage(RequestOCOOrder)


# @@protoc_insertion_point(module_scope)
