# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: request_search_symbols.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='request_search_symbols.proto',
  package='rti',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x1crequest_search_symbols.proto\x12\x03rti\"\xd7\x03\n\x14RequestSearchSymbols\x12\x15\n\x0btemplate_id\x18\xe3\xb6\t \x02(\x05\x12\x12\n\x08user_msg\x18\x98\x8d\x08 \x03(\t\x12\x15\n\x0bsearch_text\x18\xc8\xa9\x07 \x01(\t\x12\x12\n\x08\x65xchange\x18\x95\xdc\x06 \x01(\t\x12\x16\n\x0cproduct_code\x18\x8d\x93\x06 \x01(\t\x12\x43\n\x0finstrument_type\x18\xa4\xdc\x06 \x01(\x0e\x32(.rti.RequestSearchSymbols.InstrumentType\x12\x34\n\x07pattern\x18\x80\xbb\t \x01(\x0e\x32!.rti.RequestSearchSymbols.Pattern\"#\n\x07Pattern\x12\n\n\x06\x45QUALS\x10\x01\x12\x0c\n\x08\x43ONTAINS\x10\x02\"\xb0\x01\n\x0eInstrumentType\x12\n\n\x06\x46UTURE\x10\x01\x12\x11\n\rFUTURE_OPTION\x10\x02\x12\x13\n\x0f\x46UTURE_STRATEGY\x10\x03\x12\n\n\x06\x45QUITY\x10\x04\x12\x11\n\rEQUITY_OPTION\x10\x05\x12\x13\n\x0f\x45QUITY_STRATEGY\x10\x06\x12\t\n\x05INDEX\x10\x07\x12\x10\n\x0cINDEX_OPTION\x10\x08\x12\n\n\x06SPREAD\x10\t\x12\r\n\tSYNTHETIC\x10\n')
)



_REQUESTSEARCHSYMBOLS_PATTERN = _descriptor.EnumDescriptor(
  name='Pattern',
  full_name='rti.RequestSearchSymbols.Pattern',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='EQUALS', index=0, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CONTAINS', index=1, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=295,
  serialized_end=330,
)
_sym_db.RegisterEnumDescriptor(_REQUESTSEARCHSYMBOLS_PATTERN)

_REQUESTSEARCHSYMBOLS_INSTRUMENTTYPE = _descriptor.EnumDescriptor(
  name='InstrumentType',
  full_name='rti.RequestSearchSymbols.InstrumentType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='FUTURE', index=0, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FUTURE_OPTION', index=1, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FUTURE_STRATEGY', index=2, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='EQUITY', index=3, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='EQUITY_OPTION', index=4, number=5,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='EQUITY_STRATEGY', index=5, number=6,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='INDEX', index=6, number=7,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='INDEX_OPTION', index=7, number=8,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SPREAD', index=8, number=9,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SYNTHETIC', index=9, number=10,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=333,
  serialized_end=509,
)
_sym_db.RegisterEnumDescriptor(_REQUESTSEARCHSYMBOLS_INSTRUMENTTYPE)


_REQUESTSEARCHSYMBOLS = _descriptor.Descriptor(
  name='RequestSearchSymbols',
  full_name='rti.RequestSearchSymbols',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='template_id', full_name='rti.RequestSearchSymbols.template_id', index=0,
      number=154467, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='user_msg', full_name='rti.RequestSearchSymbols.user_msg', index=1,
      number=132760, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='search_text', full_name='rti.RequestSearchSymbols.search_text', index=2,
      number=120008, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='exchange', full_name='rti.RequestSearchSymbols.exchange', index=3,
      number=110101, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='product_code', full_name='rti.RequestSearchSymbols.product_code', index=4,
      number=100749, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='instrument_type', full_name='rti.RequestSearchSymbols.instrument_type', index=5,
      number=110116, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pattern', full_name='rti.RequestSearchSymbols.pattern', index=6,
      number=155008, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _REQUESTSEARCHSYMBOLS_PATTERN,
    _REQUESTSEARCHSYMBOLS_INSTRUMENTTYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=38,
  serialized_end=509,
)

_REQUESTSEARCHSYMBOLS.fields_by_name['instrument_type'].enum_type = _REQUESTSEARCHSYMBOLS_INSTRUMENTTYPE
_REQUESTSEARCHSYMBOLS.fields_by_name['pattern'].enum_type = _REQUESTSEARCHSYMBOLS_PATTERN
_REQUESTSEARCHSYMBOLS_PATTERN.containing_type = _REQUESTSEARCHSYMBOLS
_REQUESTSEARCHSYMBOLS_INSTRUMENTTYPE.containing_type = _REQUESTSEARCHSYMBOLS
DESCRIPTOR.message_types_by_name['RequestSearchSymbols'] = _REQUESTSEARCHSYMBOLS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RequestSearchSymbols = _reflection.GeneratedProtocolMessageType('RequestSearchSymbols', (_message.Message,), dict(
  DESCRIPTOR = _REQUESTSEARCHSYMBOLS,
  __module__ = 'request_search_symbols_pb2'
  # @@protoc_insertion_point(class_scope:rti.RequestSearchSymbols)
  ))
_sym_db.RegisterMessage(RequestSearchSymbols)


# @@protoc_insertion_point(module_scope)
