# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: request_market_data_update_by_underlying.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='request_market_data_update_by_underlying.proto',
  package='rti',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n.request_market_data_update_by_underlying.proto\x12\x03rti\"\xd7\x04\n#RequestMarketDataUpdateByUnderlying\x12\x15\n\x0btemplate_id\x18\xe3\xb6\t \x02(\x05\x12\x12\n\x08user_msg\x18\x98\x8d\x08 \x03(\t\x12\x1b\n\x11underlying_symbol\x18\xa2\x95\x06 \x01(\t\x12\x12\n\x08\x65xchange\x18\x95\xdc\x06 \x01(\t\x12\x19\n\x0f\x65xpiration_date\x18\xe3\x8d\x06 \x01(\t\x12\x43\n\x07request\x18\xa0\x8d\x06 \x01(\x0e\x32\x30.rti.RequestMarketDataUpdateByUnderlying.Request\x12\x15\n\x0bupdate_bits\x18\xe3\xb4\t \x01(\r\"\xb1\x02\n\nUpdateBits\x12\x0e\n\nLAST_TRADE\x10\x01\x12\x07\n\x03\x42\x42O\x10\x02\x12\x0e\n\nORDER_BOOK\x10\x04\x12\x08\n\x04OPEN\x10\x08\x12\x15\n\x11OPENING_INDICATOR\x10\x10\x12\x0c\n\x08HIGH_LOW\x10 \x12\x14\n\x10HIGH_BID_LOW_ASK\x10@\x12\n\n\x05\x43LOSE\x10\x80\x01\x12\x16\n\x11\x43LOSING_INDICATOR\x10\x80\x02\x12\x0f\n\nSETTLEMENT\x10\x80\x04\x12\x10\n\x0bMARKET_MODE\x10\x80\x08\x12\x12\n\rOPEN_INTEREST\x10\x80\x10\x12\x10\n\x0bMARGIN_RATE\x10\x80 \x12\x15\n\x10HIGH_PRICE_LIMIT\x10\x80@\x12\x15\n\x0fLOW_PRICE_LIMIT\x10\x80\x80\x01\x12\x1a\n\x14PROJECTED_SETTLEMENT\x10\x80\x80\x02\")\n\x07Request\x12\r\n\tSUBSCRIBE\x10\x01\x12\x0f\n\x0bUNSUBSCRIBE\x10\x02')
)



_REQUESTMARKETDATAUPDATEBYUNDERLYING_UPDATEBITS = _descriptor.EnumDescriptor(
  name='UpdateBits',
  full_name='rti.RequestMarketDataUpdateByUnderlying.UpdateBits',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='LAST_TRADE', index=0, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BBO', index=1, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ORDER_BOOK', index=2, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='OPEN', index=3, number=8,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='OPENING_INDICATOR', index=4, number=16,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='HIGH_LOW', index=5, number=32,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='HIGH_BID_LOW_ASK', index=6, number=64,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CLOSE', index=7, number=128,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CLOSING_INDICATOR', index=8, number=256,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SETTLEMENT', index=9, number=512,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MARKET_MODE', index=10, number=1024,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='OPEN_INTEREST', index=11, number=2048,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MARGIN_RATE', index=12, number=4096,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='HIGH_PRICE_LIMIT', index=13, number=8192,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LOW_PRICE_LIMIT', index=14, number=16384,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PROJECTED_SETTLEMENT', index=15, number=32768,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=307,
  serialized_end=612,
)
_sym_db.RegisterEnumDescriptor(_REQUESTMARKETDATAUPDATEBYUNDERLYING_UPDATEBITS)

_REQUESTMARKETDATAUPDATEBYUNDERLYING_REQUEST = _descriptor.EnumDescriptor(
  name='Request',
  full_name='rti.RequestMarketDataUpdateByUnderlying.Request',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SUBSCRIBE', index=0, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='UNSUBSCRIBE', index=1, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=614,
  serialized_end=655,
)
_sym_db.RegisterEnumDescriptor(_REQUESTMARKETDATAUPDATEBYUNDERLYING_REQUEST)


_REQUESTMARKETDATAUPDATEBYUNDERLYING = _descriptor.Descriptor(
  name='RequestMarketDataUpdateByUnderlying',
  full_name='rti.RequestMarketDataUpdateByUnderlying',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='template_id', full_name='rti.RequestMarketDataUpdateByUnderlying.template_id', index=0,
      number=154467, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='user_msg', full_name='rti.RequestMarketDataUpdateByUnderlying.user_msg', index=1,
      number=132760, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='underlying_symbol', full_name='rti.RequestMarketDataUpdateByUnderlying.underlying_symbol', index=2,
      number=101026, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='exchange', full_name='rti.RequestMarketDataUpdateByUnderlying.exchange', index=3,
      number=110101, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='expiration_date', full_name='rti.RequestMarketDataUpdateByUnderlying.expiration_date', index=4,
      number=100067, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='request', full_name='rti.RequestMarketDataUpdateByUnderlying.request', index=5,
      number=100000, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='update_bits', full_name='rti.RequestMarketDataUpdateByUnderlying.update_bits', index=6,
      number=154211, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _REQUESTMARKETDATAUPDATEBYUNDERLYING_UPDATEBITS,
    _REQUESTMARKETDATAUPDATEBYUNDERLYING_REQUEST,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=56,
  serialized_end=655,
)

_REQUESTMARKETDATAUPDATEBYUNDERLYING.fields_by_name['request'].enum_type = _REQUESTMARKETDATAUPDATEBYUNDERLYING_REQUEST
_REQUESTMARKETDATAUPDATEBYUNDERLYING_UPDATEBITS.containing_type = _REQUESTMARKETDATAUPDATEBYUNDERLYING
_REQUESTMARKETDATAUPDATEBYUNDERLYING_REQUEST.containing_type = _REQUESTMARKETDATAUPDATEBYUNDERLYING
DESCRIPTOR.message_types_by_name['RequestMarketDataUpdateByUnderlying'] = _REQUESTMARKETDATAUPDATEBYUNDERLYING
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RequestMarketDataUpdateByUnderlying = _reflection.GeneratedProtocolMessageType('RequestMarketDataUpdateByUnderlying', (_message.Message,), dict(
  DESCRIPTOR = _REQUESTMARKETDATAUPDATEBYUNDERLYING,
  __module__ = 'request_market_data_update_by_underlying_pb2'
  # @@protoc_insertion_point(class_scope:rti.RequestMarketDataUpdateByUnderlying)
  ))
_sym_db.RegisterMessage(RequestMarketDataUpdateByUnderlying)


# @@protoc_insertion_point(module_scope)
