# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: request_list_unaccepted_agreements.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='request_list_unaccepted_agreements.proto',
  package='rti',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n(request_list_unaccepted_agreements.proto\x12\x03rti\"L\n\x1fRequestListUnacceptedAgreements\x12\x15\n\x0btemplate_id\x18\xe3\xb6\t \x02(\x05\x12\x12\n\x08user_msg\x18\x98\x8d\x08 \x03(\t')
)




_REQUESTLISTUNACCEPTEDAGREEMENTS = _descriptor.Descriptor(
  name='RequestListUnacceptedAgreements',
  full_name='rti.RequestListUnacceptedAgreements',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='template_id', full_name='rti.RequestListUnacceptedAgreements.template_id', index=0,
      number=154467, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='user_msg', full_name='rti.RequestListUnacceptedAgreements.user_msg', index=1,
      number=132760, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=49,
  serialized_end=125,
)

DESCRIPTOR.message_types_by_name['RequestListUnacceptedAgreements'] = _REQUESTLISTUNACCEPTEDAGREEMENTS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RequestListUnacceptedAgreements = _reflection.GeneratedProtocolMessageType('RequestListUnacceptedAgreements', (_message.Message,), dict(
  DESCRIPTOR = _REQUESTLISTUNACCEPTEDAGREEMENTS,
  __module__ = 'request_list_unaccepted_agreements_pb2'
  # @@protoc_insertion_point(class_scope:rti.RequestListUnacceptedAgreements)
  ))
_sym_db.RegisterMessage(RequestListUnacceptedAgreements)


# @@protoc_insertion_point(module_scope)
