# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: request_tick_bar_update.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='request_tick_bar_update.proto',
  package='rti',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x1drequest_tick_bar_update.proto\x12\x03rti\"\x81\x04\n\x14RequestTickBarUpdate\x12\x15\n\x0btemplate_id\x18\xe3\xb6\t \x02(\x05\x12\x12\n\x08user_msg\x18\x98\x8d\x08 \x03(\t\x12\x10\n\x06symbol\x18\x94\xdc\x06 \x01(\t\x12\x12\n\x08\x65xchange\x18\x95\xdc\x06 \x01(\t\x12\x34\n\x07request\x18\xa0\x8d\x06 \x01(\x0e\x32!.rti.RequestTickBarUpdate.Request\x12\x35\n\x08\x62\x61r_type\x18\xa0\xa3\x07 \x01(\x0e\x32!.rti.RequestTickBarUpdate.BarType\x12<\n\x0c\x62\x61r_sub_type\x18\xa8\xa3\x07 \x01(\x0e\x32$.rti.RequestTickBarUpdate.BarSubType\x12\x1c\n\x12\x62\x61r_type_specifier\x18\xc2\x85\t \x01(\t\x12!\n\x17\x63ustom_session_open_ssm\x18\xa9\xa3\x07 \x01(\x05\x12\"\n\x18\x63ustom_session_close_ssm\x18\xaa\xa3\x07 \x01(\x05\"6\n\x07\x42\x61rType\x12\x0c\n\x08TICK_BAR\x10\x01\x12\r\n\tRANGE_BAR\x10\x02\x12\x0e\n\nVOLUME_BAR\x10\x03\"%\n\nBarSubType\x12\x0b\n\x07REGULAR\x10\x01\x12\n\n\x06\x43USTOM\x10\x02\")\n\x07Request\x12\r\n\tSUBSCRIBE\x10\x01\x12\x0f\n\x0bUNSUBSCRIBE\x10\x02')
)



_REQUESTTICKBARUPDATE_BARTYPE = _descriptor.EnumDescriptor(
  name='BarType',
  full_name='rti.RequestTickBarUpdate.BarType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='TICK_BAR', index=0, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RANGE_BAR', index=1, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='VOLUME_BAR', index=2, number=3,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=416,
  serialized_end=470,
)
_sym_db.RegisterEnumDescriptor(_REQUESTTICKBARUPDATE_BARTYPE)

_REQUESTTICKBARUPDATE_BARSUBTYPE = _descriptor.EnumDescriptor(
  name='BarSubType',
  full_name='rti.RequestTickBarUpdate.BarSubType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='REGULAR', index=0, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CUSTOM', index=1, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=472,
  serialized_end=509,
)
_sym_db.RegisterEnumDescriptor(_REQUESTTICKBARUPDATE_BARSUBTYPE)

_REQUESTTICKBARUPDATE_REQUEST = _descriptor.EnumDescriptor(
  name='Request',
  full_name='rti.RequestTickBarUpdate.Request',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SUBSCRIBE', index=0, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='UNSUBSCRIBE', index=1, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=511,
  serialized_end=552,
)
_sym_db.RegisterEnumDescriptor(_REQUESTTICKBARUPDATE_REQUEST)


_REQUESTTICKBARUPDATE = _descriptor.Descriptor(
  name='RequestTickBarUpdate',
  full_name='rti.RequestTickBarUpdate',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='template_id', full_name='rti.RequestTickBarUpdate.template_id', index=0,
      number=154467, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='user_msg', full_name='rti.RequestTickBarUpdate.user_msg', index=1,
      number=132760, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='symbol', full_name='rti.RequestTickBarUpdate.symbol', index=2,
      number=110100, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='exchange', full_name='rti.RequestTickBarUpdate.exchange', index=3,
      number=110101, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='request', full_name='rti.RequestTickBarUpdate.request', index=4,
      number=100000, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='bar_type', full_name='rti.RequestTickBarUpdate.bar_type', index=5,
      number=119200, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='bar_sub_type', full_name='rti.RequestTickBarUpdate.bar_sub_type', index=6,
      number=119208, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='bar_type_specifier', full_name='rti.RequestTickBarUpdate.bar_type_specifier', index=7,
      number=148162, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='custom_session_open_ssm', full_name='rti.RequestTickBarUpdate.custom_session_open_ssm', index=8,
      number=119209, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='custom_session_close_ssm', full_name='rti.RequestTickBarUpdate.custom_session_close_ssm', index=9,
      number=119210, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _REQUESTTICKBARUPDATE_BARTYPE,
    _REQUESTTICKBARUPDATE_BARSUBTYPE,
    _REQUESTTICKBARUPDATE_REQUEST,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=39,
  serialized_end=552,
)

_REQUESTTICKBARUPDATE.fields_by_name['request'].enum_type = _REQUESTTICKBARUPDATE_REQUEST
_REQUESTTICKBARUPDATE.fields_by_name['bar_type'].enum_type = _REQUESTTICKBARUPDATE_BARTYPE
_REQUESTTICKBARUPDATE.fields_by_name['bar_sub_type'].enum_type = _REQUESTTICKBARUPDATE_BARSUBTYPE
_REQUESTTICKBARUPDATE_BARTYPE.containing_type = _REQUESTTICKBARUPDATE
_REQUESTTICKBARUPDATE_BARSUBTYPE.containing_type = _REQUESTTICKBARUPDATE
_REQUESTTICKBARUPDATE_REQUEST.containing_type = _REQUESTTICKBARUPDATE
DESCRIPTOR.message_types_by_name['RequestTickBarUpdate'] = _REQUESTTICKBARUPDATE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RequestTickBarUpdate = _reflection.GeneratedProtocolMessageType('RequestTickBarUpdate', (_message.Message,), dict(
  DESCRIPTOR = _REQUESTTICKBARUPDATE,
  __module__ = 'request_tick_bar_update_pb2'
  # @@protoc_insertion_point(class_scope:rti.RequestTickBarUpdate)
  ))
_sym_db.RegisterMessage(RequestTickBarUpdate)


# @@protoc_insertion_point(module_scope)
