# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: response_historical_last_trade.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='response_historical_last_trade.proto',
  package='rti',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n$response_historical_last_trade.proto\x12\x03rti\"\xcd\x04\n\x1bResponseHistoricalLastTrade\x12\x15\n\x0btemplate_id\x18\xe3\xb6\t \x02(\x05\x12\x12\n\x08user_msg\x18\x98\x8d\x08 \x03(\t\x12\x1c\n\x12rq_handler_rp_code\x18\x9c\x8d\x08 \x03(\t\x12\x11\n\x07rp_code\x18\x9e\x8d\x08 \x03(\t\x12\x10\n\x06symbol\x18\x94\xdc\x06 \x01(\t\x12\x12\n\x08\x65xchange\x18\x95\xdc\x06 \x01(\t\x12\x17\n\rpresence_bits\x18\x92\x8d\t \x01(\r\x12\x14\n\nclear_bits\x18\xcb\xb7\t \x01(\r\x12\x15\n\x0bis_snapshot\x18\xa9\xdc\x06 \x01(\x08\x12\x15\n\x0btrade_price\x18\xa6\x8d\x06 \x01(\x01\x12\x14\n\ntrade_size\x18\xd2\x8e\x06 \x01(\x05\x12\x45\n\taggressor\x18\x83\xeb\x06 \x01(\x0e\x32\x30.rti.ResponseHistoricalLastTrade.TransactionType\x12\x14\n\nnet_change\x18\xab\x8d\x06 \x01(\x01\x12\x18\n\x0epercent_change\x18\xd8\x8d\x06 \x01(\x01\x12\x10\n\x06volume\x18\xc0\x8d\x06 \x01(\x04\x12\x0e\n\x04vwap\x18\x83\x98\x06 \x01(\x01\x12\x0f\n\x05ssboe\x18\xd4\x94\t \x01(\x05\x12\x0f\n\x05usecs\x18\xd5\x94\t \x01(\x05\"X\n\x0cPresenceBits\x12\x0e\n\nLAST_TRADE\x10\x01\x12\x0e\n\nNET_CHANGE\x10\x02\x12\x12\n\x0ePRECENT_CHANGE\x10\x04\x12\n\n\x06VOLUME\x10\x08\x12\x08\n\x04VWAP\x10\x10\"$\n\x0fTransactionType\x12\x07\n\x03\x42UY\x10\x01\x12\x08\n\x04SELL\x10\x02')
)



_RESPONSEHISTORICALLASTTRADE_PRESENCEBITS = _descriptor.EnumDescriptor(
  name='PresenceBits',
  full_name='rti.ResponseHistoricalLastTrade.PresenceBits',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='LAST_TRADE', index=0, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='NET_CHANGE', index=1, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PRECENT_CHANGE', index=2, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='VOLUME', index=3, number=8,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='VWAP', index=4, number=16,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=509,
  serialized_end=597,
)
_sym_db.RegisterEnumDescriptor(_RESPONSEHISTORICALLASTTRADE_PRESENCEBITS)

_RESPONSEHISTORICALLASTTRADE_TRANSACTIONTYPE = _descriptor.EnumDescriptor(
  name='TransactionType',
  full_name='rti.ResponseHistoricalLastTrade.TransactionType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='BUY', index=0, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SELL', index=1, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=599,
  serialized_end=635,
)
_sym_db.RegisterEnumDescriptor(_RESPONSEHISTORICALLASTTRADE_TRANSACTIONTYPE)


_RESPONSEHISTORICALLASTTRADE = _descriptor.Descriptor(
  name='ResponseHistoricalLastTrade',
  full_name='rti.ResponseHistoricalLastTrade',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='template_id', full_name='rti.ResponseHistoricalLastTrade.template_id', index=0,
      number=154467, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='user_msg', full_name='rti.ResponseHistoricalLastTrade.user_msg', index=1,
      number=132760, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rq_handler_rp_code', full_name='rti.ResponseHistoricalLastTrade.rq_handler_rp_code', index=2,
      number=132764, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rp_code', full_name='rti.ResponseHistoricalLastTrade.rp_code', index=3,
      number=132766, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='symbol', full_name='rti.ResponseHistoricalLastTrade.symbol', index=4,
      number=110100, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='exchange', full_name='rti.ResponseHistoricalLastTrade.exchange', index=5,
      number=110101, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='presence_bits', full_name='rti.ResponseHistoricalLastTrade.presence_bits', index=6,
      number=149138, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='clear_bits', full_name='rti.ResponseHistoricalLastTrade.clear_bits', index=7,
      number=154571, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='is_snapshot', full_name='rti.ResponseHistoricalLastTrade.is_snapshot', index=8,
      number=110121, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='trade_price', full_name='rti.ResponseHistoricalLastTrade.trade_price', index=9,
      number=100006, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='trade_size', full_name='rti.ResponseHistoricalLastTrade.trade_size', index=10,
      number=100178, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='aggressor', full_name='rti.ResponseHistoricalLastTrade.aggressor', index=11,
      number=112003, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='net_change', full_name='rti.ResponseHistoricalLastTrade.net_change', index=12,
      number=100011, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='percent_change', full_name='rti.ResponseHistoricalLastTrade.percent_change', index=13,
      number=100056, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='volume', full_name='rti.ResponseHistoricalLastTrade.volume', index=14,
      number=100032, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='vwap', full_name='rti.ResponseHistoricalLastTrade.vwap', index=15,
      number=101379, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ssboe', full_name='rti.ResponseHistoricalLastTrade.ssboe', index=16,
      number=150100, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='usecs', full_name='rti.ResponseHistoricalLastTrade.usecs', index=17,
      number=150101, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _RESPONSEHISTORICALLASTTRADE_PRESENCEBITS,
    _RESPONSEHISTORICALLASTTRADE_TRANSACTIONTYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=46,
  serialized_end=635,
)

_RESPONSEHISTORICALLASTTRADE.fields_by_name['aggressor'].enum_type = _RESPONSEHISTORICALLASTTRADE_TRANSACTIONTYPE
_RESPONSEHISTORICALLASTTRADE_PRESENCEBITS.containing_type = _RESPONSEHISTORICALLASTTRADE
_RESPONSEHISTORICALLASTTRADE_TRANSACTIONTYPE.containing_type = _RESPONSEHISTORICALLASTTRADE
DESCRIPTOR.message_types_by_name['ResponseHistoricalLastTrade'] = _RESPONSEHISTORICALLASTTRADE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ResponseHistoricalLastTrade = _reflection.GeneratedProtocolMessageType('ResponseHistoricalLastTrade', (_message.Message,), dict(
  DESCRIPTOR = _RESPONSEHISTORICALLASTTRADE,
  __module__ = 'response_historical_last_trade_pb2'
  # @@protoc_insertion_point(class_scope:rti.ResponseHistoricalLastTrade)
  ))
_sym_db.RegisterMessage(ResponseHistoricalLastTrade)


# @@protoc_insertion_point(module_scope)
