# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: response_tick_bar_replay.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='response_tick_bar_replay.proto',
  package='rti',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x1eresponse_tick_bar_replay.proto\x12\x03rti\"\xd8\x04\n\x15ResponseTickBarReplay\x12\x15\n\x0btemplate_id\x18\xe3\xb6\t \x02(\x05\x12\x12\n\x08user_msg\x18\x98\x8d\x08 \x03(\t\x12\x1c\n\x12rq_handler_rp_code\x18\x9c\x8d\x08 \x03(\t\x12\x11\n\x07rp_code\x18\x9e\x8d\x08 \x03(\t\x12\x10\n\x06symbol\x18\x94\xdc\x06 \x01(\t\x12\x12\n\x08\x65xchange\x18\x95\xdc\x06 \x01(\t\x12\x32\n\x04type\x18\xa0\xa3\x07 \x01(\x0e\x32\".rti.ResponseTickBarReplay.BarType\x12\x39\n\x08sub_type\x18\xa8\xa3\x07 \x01(\x0e\x32%.rti.ResponseTickBarReplay.BarSubType\x12\x18\n\x0etype_specifier\x18\xc2\x85\t \x01(\t\x12\x14\n\nnum_trades\x18\xa4\xa3\x07 \x01(\x04\x12\x10\n\x06volume\x18\xa5\xa3\x07 \x01(\x04\x12\x14\n\nopen_price\x18\xb3\x8d\x06 \x01(\x01\x12\x15\n\x0b\x63lose_price\x18\xb5\x8d\x06 \x01(\x01\x12\x14\n\nhigh_price\x18\xac\x8d\x06 \x01(\x01\x12\x13\n\tlow_price\x18\xad\x8d\x06 \x01(\x01\x12!\n\x17\x63ustom_session_open_ssm\x18\xa9\xa3\x07 \x01(\x05\x12\x18\n\x0e\x64\x61ta_bar_ssboe\x18\xa2\xa3\x07 \x03(\x05\x12\x18\n\x0e\x64\x61ta_bar_usecs\x18\xa3\xa3\x07 \x03(\x05\"6\n\x07\x42\x61rType\x12\x0c\n\x08TICK_BAR\x10\x01\x12\r\n\tRANGE_BAR\x10\x02\x12\x0e\n\nVOLUME_BAR\x10\x03\"%\n\nBarSubType\x12\x0b\n\x07REGULAR\x10\x01\x12\n\n\x06\x43USTOM\x10\x02')
)



_RESPONSETICKBARREPLAY_BARTYPE = _descriptor.EnumDescriptor(
  name='BarType',
  full_name='rti.ResponseTickBarReplay.BarType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='TICK_BAR', index=0, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RANGE_BAR', index=1, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='VOLUME_BAR', index=2, number=3,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=547,
  serialized_end=601,
)
_sym_db.RegisterEnumDescriptor(_RESPONSETICKBARREPLAY_BARTYPE)

_RESPONSETICKBARREPLAY_BARSUBTYPE = _descriptor.EnumDescriptor(
  name='BarSubType',
  full_name='rti.ResponseTickBarReplay.BarSubType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='REGULAR', index=0, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CUSTOM', index=1, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=603,
  serialized_end=640,
)
_sym_db.RegisterEnumDescriptor(_RESPONSETICKBARREPLAY_BARSUBTYPE)


_RESPONSETICKBARREPLAY = _descriptor.Descriptor(
  name='ResponseTickBarReplay',
  full_name='rti.ResponseTickBarReplay',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='template_id', full_name='rti.ResponseTickBarReplay.template_id', index=0,
      number=154467, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='user_msg', full_name='rti.ResponseTickBarReplay.user_msg', index=1,
      number=132760, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rq_handler_rp_code', full_name='rti.ResponseTickBarReplay.rq_handler_rp_code', index=2,
      number=132764, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rp_code', full_name='rti.ResponseTickBarReplay.rp_code', index=3,
      number=132766, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='symbol', full_name='rti.ResponseTickBarReplay.symbol', index=4,
      number=110100, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='exchange', full_name='rti.ResponseTickBarReplay.exchange', index=5,
      number=110101, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='rti.ResponseTickBarReplay.type', index=6,
      number=119200, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sub_type', full_name='rti.ResponseTickBarReplay.sub_type', index=7,
      number=119208, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type_specifier', full_name='rti.ResponseTickBarReplay.type_specifier', index=8,
      number=148162, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='num_trades', full_name='rti.ResponseTickBarReplay.num_trades', index=9,
      number=119204, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='volume', full_name='rti.ResponseTickBarReplay.volume', index=10,
      number=119205, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='open_price', full_name='rti.ResponseTickBarReplay.open_price', index=11,
      number=100019, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='close_price', full_name='rti.ResponseTickBarReplay.close_price', index=12,
      number=100021, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='high_price', full_name='rti.ResponseTickBarReplay.high_price', index=13,
      number=100012, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='low_price', full_name='rti.ResponseTickBarReplay.low_price', index=14,
      number=100013, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='custom_session_open_ssm', full_name='rti.ResponseTickBarReplay.custom_session_open_ssm', index=15,
      number=119209, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data_bar_ssboe', full_name='rti.ResponseTickBarReplay.data_bar_ssboe', index=16,
      number=119202, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data_bar_usecs', full_name='rti.ResponseTickBarReplay.data_bar_usecs', index=17,
      number=119203, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _RESPONSETICKBARREPLAY_BARTYPE,
    _RESPONSETICKBARREPLAY_BARSUBTYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=40,
  serialized_end=640,
)

_RESPONSETICKBARREPLAY.fields_by_name['type'].enum_type = _RESPONSETICKBARREPLAY_BARTYPE
_RESPONSETICKBARREPLAY.fields_by_name['sub_type'].enum_type = _RESPONSETICKBARREPLAY_BARSUBTYPE
_RESPONSETICKBARREPLAY_BARTYPE.containing_type = _RESPONSETICKBARREPLAY
_RESPONSETICKBARREPLAY_BARSUBTYPE.containing_type = _RESPONSETICKBARREPLAY
DESCRIPTOR.message_types_by_name['ResponseTickBarReplay'] = _RESPONSETICKBARREPLAY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ResponseTickBarReplay = _reflection.GeneratedProtocolMessageType('ResponseTickBarReplay', (_message.Message,), dict(
  DESCRIPTOR = _RESPONSETICKBARREPLAY,
  __module__ = 'response_tick_bar_replay_pb2'
  # @@protoc_insertion_point(class_scope:rti.ResponseTickBarReplay)
  ))
_sym_db.RegisterMessage(ResponseTickBarReplay)


# @@protoc_insertion_point(module_scope)
