# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: response_list_exchange_permissions.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='response_list_exchange_permissions.proto',
  package='rti',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n(response_list_exchange_permissions.proto\x12\x03rti\"\x91\x02\n\x1fResponseListExchangePermissions\x12\x15\n\x0btemplate_id\x18\xe3\xb6\t \x02(\x05\x12\x12\n\x08user_msg\x18\x98\x8d\x08 \x03(\t\x12\x1c\n\x12rq_handler_rp_code\x18\x9c\x8d\x08 \x03(\t\x12\x11\n\x07rp_code\x18\x9e\x8d\x08 \x03(\t\x12\x12\n\x08\x65xchange\x18\x95\xdc\x06 \x01(\t\x12P\n\x10\x65ntitlement_flag\x18\xb8\xae\t \x01(\x0e\x32\x34.rti.ResponseListExchangePermissions.EntitlementFlag\",\n\x0f\x45ntitlementFlag\x12\x0b\n\x07\x45NABLED\x10\x01\x12\x0c\n\x08\x44ISABLED\x10\x02')
)



_RESPONSELISTEXCHANGEPERMISSIONS_ENTITLEMENTFLAG = _descriptor.EnumDescriptor(
  name='EntitlementFlag',
  full_name='rti.ResponseListExchangePermissions.EntitlementFlag',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ENABLED', index=0, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DISABLED', index=1, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=279,
  serialized_end=323,
)
_sym_db.RegisterEnumDescriptor(_RESPONSELISTEXCHANGEPERMISSIONS_ENTITLEMENTFLAG)


_RESPONSELISTEXCHANGEPERMISSIONS = _descriptor.Descriptor(
  name='ResponseListExchangePermissions',
  full_name='rti.ResponseListExchangePermissions',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='template_id', full_name='rti.ResponseListExchangePermissions.template_id', index=0,
      number=154467, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='user_msg', full_name='rti.ResponseListExchangePermissions.user_msg', index=1,
      number=132760, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rq_handler_rp_code', full_name='rti.ResponseListExchangePermissions.rq_handler_rp_code', index=2,
      number=132764, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rp_code', full_name='rti.ResponseListExchangePermissions.rp_code', index=3,
      number=132766, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='exchange', full_name='rti.ResponseListExchangePermissions.exchange', index=4,
      number=110101, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='entitlement_flag', full_name='rti.ResponseListExchangePermissions.entitlement_flag', index=5,
      number=153400, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _RESPONSELISTEXCHANGEPERMISSIONS_ENTITLEMENTFLAG,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=50,
  serialized_end=323,
)

_RESPONSELISTEXCHANGEPERMISSIONS.fields_by_name['entitlement_flag'].enum_type = _RESPONSELISTEXCHANGEPERMISSIONS_ENTITLEMENTFLAG
_RESPONSELISTEXCHANGEPERMISSIONS_ENTITLEMENTFLAG.containing_type = _RESPONSELISTEXCHANGEPERMISSIONS
DESCRIPTOR.message_types_by_name['ResponseListExchangePermissions'] = _RESPONSELISTEXCHANGEPERMISSIONS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ResponseListExchangePermissions = _reflection.GeneratedProtocolMessageType('ResponseListExchangePermissions', (_message.Message,), dict(
  DESCRIPTOR = _RESPONSELISTEXCHANGEPERMISSIONS,
  __module__ = 'response_list_exchange_permissions_pb2'
  # @@protoc_insertion_point(class_scope:rti.ResponseListExchangePermissions)
  ))
_sym_db.RegisterMessage(ResponseListExchangePermissions)


# @@protoc_insertion_point(module_scope)
